### ISSUE TITLE
Excitation Energies and Probabilities

### ISSUE THREAD

**Issue by tjcarroll3** [marc1uk/INSS_Katrina_Sterile#1]
Hi Gang,

We need to digitize a table in order to get the beta spectrum. A version is in this paper: https://journals.aps.org/prl/pdf/10.1103/PhysRevLett.84.242

**Comment by tjcarroll3** [comment]
I was able to digitize the table in the file.

**Comment by marc1uk** [comment]
"I have problem x."
"nvm solved it."

_*but how*_???

**Comment by marc1uk** [comment]
Apparently you can do OCR in Adobe Premier Pro!
